.\" -*- mode: troff; coding: UTF-8 -*-
.TH myconnector 1  "Dec 9, 2020" "version 2.0" "USER COMMANDS"
.SH NAME
MyConnector \- remote desktop client.
.SH SYNOPSIS
.B myconnector
[options]
.SH DESCRIPTION
This is an aggregator program to connect to various servers using all of the popular remote desktop protocols (RDP, VNC, Citrix, VMware, etc).
.SH OPTIONS
.TP
\fB<not options>\fR
.RS 3
Do not specify parameters for starting the GUI.
.RE
.PP
\fB-c CONNECTION, --connection CONNECTION\fR
.RS 3
name of the saved connection
.RE
.PP
\fBFILE, -f FILE, --file FILE\fR
.RS 3
name of the file (.myc, .remmina, .rdp)
.RE
.PP
\fB-l, --list\fR
.RS 3
list of the saved connections
.RE
.PP
\fB--kiosk <option>\fR
.RS 3
KIOSK mode control ('--kiosk help' for more information)
.RE
.PP
\fB-v, --version\fR
.RS 3
show the application version
.RE
.PP
\fB-d, --debug\fR
.RS 3
show log files online
.RE
.PP
\fB-h, --help\fR
.RS 3
show help message and exit
.RE
.PP
\fB-q, --quit\fR
.RS 3
quit the application
.SH LINKS
http://myconnector.ru/
.TP
http://wiki.myconnector.ru
.SH AUTHOR
Evgeniy Korneechev <ek@myconnector.ru>
