.\" -*- mode: troff; coding: UTF-8 -*-
.TH myconnector 1  "Apr 27, 2022" "version 2.3" "USER COMMANDS"
.SH NAME
MyConnector \- remote desktop client.
.SH SYNOPSIS
.B myconnector
[options]
.SH DESCRIPTION
This is an aggregator program to connect to various servers using all of the popular remote desktop protocols (RDP, VNC, Citrix, VMware, etc).
.SH OPTIONS
.TP
\fB<not options>\fR
.RS 3
GUI launch.
.RE
.PP
\fB-c CONNECTION, --connection CONNECTION\fR
.RS 3
Name of the saved connection.
.RE
.PP
\fBFILE, -f FILE, --file FILE\fR
.RS 3
Name of the file (.myc, .remmina, .rdp).
.RE
.PP
\fB-l, --list\fR
.RS 3
List of the saved connections.
.RE
.PP
\fB-e, --edit\fR
.RS 3
Edit config file.
.RE
.PP
\fB--kiosk <option>\fR
.RS 3
KIOSK mode control ('--kiosk help' for more information).
.RE
.PP
\fB-v, --version\fR
.RS 3
Show the application version.
.RE
.PP
\fB-d, --debug\fR
.RS 3
Show log files online.
.RE
.PP
\fB-h, --help\fR
.RS 3
Show help message and exit.
.RE
.PP
\fB-q, --quit\fR
.RS 3
Quit the application.
.SH LINKS
http://myconnector.ru/
.TP
https://docs.myconnector.ru/
.SH AUTHOR
Evgeniy Korneechev <ek@myconnector.ru>
