#!/bin/bash

# Checking avaiable chromium
KIOSK_COMMAND=""
for i in chromium chromium-gost yandex-browser-stable firefox; do
    which $i > /dev/null 2>&1
    if [ "$?" -eq 0 ]; then
        if [ "$i" == "firefox" ]; then
            KIOSK_COMMAND="$i --kiosk --private-window"
        else
            KIOSK_COMMAND="$i --kiosk --incognito"
        fi
        break
    fi
done

# Checking avaiable window manager
WM=""
for i in marco /usr/lib/kf5/bin/kwin_x11 openbox awesome; do
    which $i > /dev/null 2>&1
    if [ "$?" -eq 0 ]; then
        WM=$i
        break
    fi
done

